development:
  adapter: postgresql
  database: firefly_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: firefly_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: firefly
  pool: 5
  timeout: 5000
